### ISSUE TITLE
[Suggestion] Add unsupported ES6 construct

### ISSUE THREAD

**Issue by jmdyck** [rbuckton/grammarkdown#9]
There are a couple of constructs used in ES6 productions that don't appear to be supported by grammarkdown:

~~24.3.1's production for DoubleStringCharacter has the RHS:~~ *Edit: Moved to #14* - @rbuckton

B.1.4's productions for AtomEscape and ClassAtomNoDashInRange have the RHSs:
```
    [~U] DecimalEscape but only if the integer value of DecimalEscape is <= NCapturingParens

    \ ClassEscape but only if ClassEscape evaluates to a CharSet with exactly one character
```

**Comment by rbuckton** [comment]
@jmdyck I'll take a look at that, thanks.

**Comment by rbuckton** [comment]
I can probably add the U+ syntax for Unicode escapes easily enough. AtomEscape and ClassAtomNoDashInRange are interesting cases and look more like prose than simple keywords or key phrases like `one of`, `lookahead`, etc. Any suggestions on a good way to distinguish prose here? 

Generally I use the markdown block-quote marker `>` to indicate an entire RHS is prose. I could do the same here, though use of the prose marker turns off binding of Nonterminal symbols (which is used for the checker and for lookups/hyperlinking).

**Comment by rbuckton** [comment]
For example:
```
AtomEscape ::
    [~U] DecimalEscape > but only if the integer value of DecimalEscape is <= NCapturingParens
```

Alternatively, I could make `but only` a keyword/keyphrase and treat any remaining tokens on the line as prose. I could then have some kind of marker to indicate part of the prose is a Nonterminal, such as fencing the Nonterminal with `/` characters, like this:

```
AtomEscape ::
    [~U] DecimalEscape but only if the integer value of /DecimalEscape/ is <= /NCapturingParens/
```

Also, I consider the `[~U]` above as something like a zero-width assertion. As such, we could indicate this special condition as a trailing assertion:

```
AtomEscape ::
    [~U] DecimalEscape [but only if the integer value of /DecimalEscape/ is <= /NCapturingParens/]
```

This has the added advantage of allowing additional tokens after the assertion.

**Comment by jmdyck** [comment]
I think the notation
```
[but only if ...]
```
makes the most sense to me.

By the way, note that:
(1) 'NCapturingParens' isn't a nonterminal, it's a (mis-spelled) reference to 'NcapturingParens', a metavariable in the algorithms of 21.2.*
(2) In ecmarkdown, nonterminals are delimited by pipe characters, e.g. `|DecimalEscape|`, so that might be easier on readers.

**Comment by rbuckton** [comment]
The `[but only if ...]` notation doesn't scan well as the `...` here is an arbitrary string. I may need a different way to delimit this prose. One option is to use parenthesis like this:

```
AtomEscape :: [~U] DecimalEscape (but only if the integer value of |DecimalEscape| is <= NcapturingParens)
```
Currently I allow the use of both brackets and parenthesis for production parameters and arguments. I'm thinking about switching to only brackets so that I can reserve parenthesis for this purpose.

**Comment by rbuckton** [comment]
@bterlson How would I emit the above productions for EMU?

**Comment by bterlson** [comment]
The "but only if" prose would go in a gann element (without the square brackets/parens).

**Comment by jmdyck** [comment]
How is "(but only if ...)" easier to scan than "[but only if ...]" ?

**Comment by rbuckton** [comment]
Just that if I reserved () for this purpose, i could scan it like a quoted string, rather than using `if`...`]`. I have the `]` version working, just feels messy.

I was talking to @bterlson about it, and I may drop the brackets and just look for `but only if... \n`

**Comment by rbuckton** [comment]
Let me back up to my original comment:

> AtomEscape and ClassAtomNoDashInRange are interesting cases and look more like prose than simple keywords or key phrases like `one of`, `lookahead`, etc. Any suggestions on a good way to distinguish prose here? 
> 
> Generally I use the markdown block-quote marker `>` to indicate an entire RHS is prose. I could do the same here, though use of the prose marker turns off binding of Nonterminal symbols (which is used for the checker and for lookups/hyperlinking).

My main goal was to determine what was the best way to parse this sentence:

```
AtomEscape ::
    [~U] DecimalEscape but only if the integer value of DecimalEscape is <= NCapturingParens
```

I can scan the tokens `but`, `only`, `if` to recognize the start of this fragment. I then need to determine when to terminate the fragment. If I stop at LineTerminator, how would I continue a possibly long-running fragment across multiple lines. Do I need to be able to terminate the fragment but still be able to have additional symbols to the production? Is it important to be able to distinguish between raw text and things like terminals or non-terminals within the fragment?

I considered bracketing the fragment like I do with any other assertion/annotation, so that I can explicitly terminate the fragment with a trailing `]`. After having implemented it this way, I'm finding that it overcomplicates the process of parsing assertions, and makes it more cumbersome to detect things like terminals and non-terminals for the static analysis portions of GMD.

What I'm proposing is that I repurpose the open and close parenthesis symbols to mean something unique, that would be more consistent to scan. 

Consider the following:

```
AtomEscape ::
    [~U] DecimalEscape (but only if the integer value of |DecimalEscape| is <= NcapturingParens)
```

The scanner can then detect the `(` and skip forward until it encounters a `|`, `` ` ``, or `)` and produce the tokens (starting from the opening parenthesis): 

* ProseFragmentHead: `but only if the integer value of `
* Identifier: *DecimalEscape*
* ProseFragmentTail: `is <= NcapturingParens`

If given a more complex example:
```
X ::
  Y (but only if |Y| is not `z` and the integer value of |Y| is positive. Also,
       this can span multiple lines.)
```

The scanner would produce the following tokens (starting from the opening parenthesis):

* ProseFragmentHead: `but only if `
* Identifier: *Y*
* ProseFragmentMiddle: ` is not `
* Terminal: `` `z` ``
* ProseFragmentMiddle: ` and the integer value of `
* Identifier: *Y*
* ProseFragmentTail: ` is positive. Also,\n        this can span multiple lines.`

If I don't use the parenthesis, I can still scan `but only if` and advance until I reach a *LineTerminator*, but special case `|` wrapped identifiers and `` ` `` wrapped terminals. But in that case, I cannot wrap multiple lines without some other indicator.

**Comment by rbuckton** [comment]
Also, I'm going to split off the unicode character entity parsing to a separate issue that I can close out.

**Comment by bterlson** [comment]
I am fine with parens, but let's take a step back and look at the notational conventions. I'm not sure why it's `[no |LineTerminator| here]` but it's just `but not |LineTerminator|`. What if we said all of these things were parentheticals in both the input format and rendering? It also gives us a better graphical distinction from parameters...
